<?php
@define('PLUGIN_EVENT_OSM_NAME', 'Integración de OpenStreetMap');
@define('PLUGIN_EVENT_OSM_DESCRIPTION', 'Ofrece un mapa interactivo para archivos *.gpx y entradas de blog con coordenadas geográficas');
@define('PLUGIN_EVENT_OSM_NOT_SHOWN', 'No se muestra en el sitio web');
@define('PLUGIN_EVENT_STATIC_OSM_NAME', 'Archivos estáticos de OpenStreetMap');
@define('PLUGIN_EVENT_STATIC_OSM_DESCRIPTION', 'Inserta scripts y hojas de estilo para OpenStreetMap');
@define('PLUGIN_EVENT_STATIC_OSM_COMPRESS_GPX', 'Comprimir archivos GPX');
@define('PLUGIN_EVENT_STATIC_OSM_COMPRESS_GPX_DESCRIPTION', 'Elimina todos los datos innecesarios de los archivos GPX durante la carga');
@define('PLUGIN_EVENT_OSM_CATEGORY', 'Categoría');
@define('PLUGIN_EVENT_OSM_CATEGORY_DESCRIPTION', 'El mapa se muestra para esta categoría');
@define('PLUGIN_EVENT_OSM_CATEGORY_WITHOUT', 'Sin');
@define('PLUGIN_EVENT_OSM_CATEGORY_ANY', 'Cualquier');
@define('PLUGIN_EVENT_OSM_PATH', 'CarpetaPfad');
@define('PLUGIN_EVENT_OSM_PATH_DESCRIPTION', 'Carpeta para los archivos GPX, separados por saltos de línea');
@define('PLUGIN_EVENT_OSM_LAT', 'Latitud (Lat.)');
@define('PLUGIN_EVENT_OSM_LAT_DESCRIPTION', 'Latitud del centro del mapa');
@define('PLUGIN_EVENT_OSM_LONG', 'Longitud (Lon.)');
@define('PLUGIN_EVENT_OSM_LONG_DESCRIPTION', 'Longitud del centro del mapa');
@define('PLUGIN_EVENT_OSM_ZOOM', 'Zoom');
@define('PLUGIN_EVENT_OSM_ZOOM_DESCRIPTION', 'Nivel de zoom del mapa');
@define('PLUGIN_EVENT_OSM_HEIGHT', 'Altura del mapa');
@define('PLUGIN_EVENT_OSM_HEIGHT_DESCRIPTION', 'Altura del mapa con unidad CSS (px, em, etc.)');
