<?php #

@define('PLUGIN_EVENT_SOCIAL_NAME', 'Sharebuttons');
@define('PLUGIN_EVENT_SOCIAL_DESC', 'Zeige Sharebuttons für Netzwerke wie Facebook und Twitter.');
@define('PLUGIN_EVENT_SOCIAL_SERVICES', 'Unterstützte Netzwerke');
@define('PLUGIN_EVENT_SOCIAL_SERVICES_DESC', 'Wähle die Netzwerke, für die ein Share-Button angezeigt werden soll.');
@define('PLUGIN_EVENT_SOCIAL_THEME', 'Farbschema');
@define('PLUGIN_EVENT_SOCIAL_THEME_DESC', 'Wähle ein Farbschema für die Sharebuttons.');
@define('PLUGIN_EVENT_SOCIAL_THEME_STD', 'Standard');
@define('PLUGIN_EVENT_SOCIAL_THEME_WHITE', 'Weiß');
@define('PLUGIN_EVENT_SOCIAL_THEME_GREY', 'Grau');
@define('PLUGIN_EVENT_SOCIAL_SIZE', 'Buttongröße');
@define('PLUGIN_EVENT_SOCIAL_SIZE_DESC', 'Wähle eine Größe für die Sharebuttons.');
@define('PLUGIN_EVENT_SOCIAL_SIZE_STD', 'Standard');
@define('PLUGIN_EVENT_SOCIAL_SIZE_ICONS', 'Nur die Icons');
@define('PLUGIN_EVENT_SOCIAL_OVERVIEW', 'Auf Übersichtsseiten anzeigen');
@define('PLUGIN_EVENT_SOCIAL_OVERVIEW_DESC', 'Zeige die Sharebuttons auch auf Übersichtsseiten (wie z.B. der Startseite).');
@define('PLUGIN_EVENT_SOCIAL_TWITTERVIA', 'Twittererwähnung');
@define('PLUGIN_EVENT_SOCIAL_TWITTERVIA_DESC', 'Twittername, der am Ende des Tweets angehängt werden soll ("none" deaktiviert dies).');
@define('PLUGIN_EVENT_SOCIAL_MASTODONVIA', 'Mastodonerwähnung');
@define('PLUGIN_EVENT_SOCIAL_MASTODONVIA_DESC', 'Mastodonname, der am Ende des Toots angehängt werden soll ("none" deaktiviert dies).');
@define('PLUGIN_EVENT_SOCIAL_BLUESKYVIA', 'Blueskyerwähnung');
@define('PLUGIN_EVENT_SOCIAL_BLUESKYVIA_DESC', 'Blueskyname, der am Ende des Tweets angehängt werden soll ("none" deaktiviert dies).');
@define('PLUGIN_EVENT_SOCIAL_IMAGE', 'Fallback-Bild');
@define('PLUGIN_EVENT_SOCIAL_IMAGE_DESC', 'Ein Bild, das auf Twitter und Facebook angezeigt wird, wenn der Eintrag kein eigenes Bild erhält. "none" deaktiviert es.');
@define('PLUGIN_EVENT_SOCIAL_ENTRY_IMAGE', 'Bild für Social Media');
@define('PLUGIN_EVENT_SOCIAL_SHARE_TITLE', 'Bei %s teilen');
@define('PLUGIN_EVENT_SOCIAL_SHARE_ACTION', 'Teilen');
@define('PLUGIN_EVENT_SOCIAL_SHARE_TITLE_POCKET', 'Bei Pocket speichern');
@define('PLUGIN_EVENT_SOCIAL_SHARE_TITLE_PINTEREST', 'Bei Pinterest pinnen');
@define('PLUGIN_EVENT_SOCIAL_SHARE_TITLE_MAIL', 'Mit Mail senden');
