<?php # $Id: lang_cz.inc.php,v 1.2 2007/12/03 11:30:04 garvinhicking Exp $

/**
 *  @version $Revision: 1.2 $
 *  @author Vladimír Ajgl <vlada@ajgl.cz>
 *  EN-Revision: Revision of lang_en.inc.php
 *  Translated on 2007/11/30
 */

@define('PLUGIN_MYMOOD_TITLE',                  'Moje nálada');
@define('PLUGIN_MYMOOD_DESC',                   'Umo¾òuje vám pøidávat va¹í momentální náladu nebo nálady k pøíspvìkùm.');
@define('PLUGIN_MYMOOD_MOOD_MISSINGDATA',       'Chybí u¾ivatelský vstup');
@define('PLUGIN_MYMOOD_MOOD_LIST',              'Toto je seznam pøístupných nálad.');
@define('PLUGIN_MYMOOD_MOOD_NAME',              'Jméno nálady');
@define('PLUGIN_MYMOOD_MOOD_IMG',               'Obrázek nálady.  (Relativní adresa vzheldem k základnímu adresáøi serendipity nebo plná absolutní URL adresa)');
@define('PLUGIN_MYMOOD_MOOD_ASCII',             'Textová repreznetace smajlíka nálady');
@define('PLUGIN_MYMOOD_MOOD_DELETE',            'Samzat');
@define('PLUGIN_MYMOOD_CONFIRM_RESET_BUTTON',   'Obnovit pùvodní nálady');
@define('PLUGIN_MYMOOD_CONFIRM_RESET',          'Opravdu chcete obnovit pùvodní nálady? Tento pøíkaz sma¾e v¹echny Va¹e nastavené nálady a nastaví místo nich pøednastavené.  \n\nVAROVÁNÍ: Smazání Vámi nastavených nálad mù¾e vést k zobrazování ¹patných nálad u starých pøíspìvkù!');

@define('PLUGIN_MYMOOD_INTRO',                  'Intro');
@define('PLUGIN_MYMOOD_INTRO_DESC',             'Intro je text, který uvozuje seznam Va¹í nálady. Napøíklad "Moje nálada:"');
@define('PLUGIN_MYMOOD_OUTRO',                  'Outro');
@define('PLUGIN_MYMOOD_OUTRO_DESC',             'Podobnì jako intro text');
@define('PLUGIN_MYMOOD_TODAY_I_FEEL',           'Moje nálada:');
@define('PLUGIN_MYMOOD_PLACE_FIELD',            'Umístít blízko');
@define('PLUGIN_MYMOOD_PLACE_FIELD_DESC',       'Poblí¾ které èásti pøíspìvku se má nálada zobrazit?');
@define('PLUGIN_MYMOOD_PLACE_FIELD_BODY',       'Tìlo pøíspìveku');
@define('PLUGIN_MYMOOD_PLACE_FIELD_AUTHOR',     'Autor');
@define('PLUGIN_MYMOOD_PLACE_FIELD_TITLE',      'Nadpis');
@define('PLUGIN_MYMOOD_PLACE_FIELD_FOOTER',     'Záhlaví');
@define('PLUGIN_MYMOOD_PLACE_BEFORE',           'Umístit pøed');
@define('PLUGIN_MYMOOD_PLACE_BEFORE_DESC',      'Umístit náladu pøed vybrané pole? Pokud je vybráno NE, umístí se za pole.');
@define('PLUGIN_MYMOOD_DISPLAY_FORMAT',         'Formát zobrazení');
@define('PLUGIN_MYMOOD_DISPLAY_FORMAT_DESC',    'Formát zobrazení nálady. Mù¾ete ou¾ít pole {name}, {img} a {ascii} v jakémkoliv poøadí a mno¾ství k zobrazení nálad podle Va¹ich pøání. Toto nebude mít vliv na umístìní nálady v nadpisu. Mù¾ete zadávat i hteml. (Standardnì: {img} {name})');
@define('PLUGIN_MYMOOD_MORE_NEW_MOODS',         'Dal¹í nové nálady');
@define('PLUGIN_MYMOOD_NEW_MOOD',               'Nová nálada (název)');
@define('PLUGIN_MYMOOD_NEW_ASCII',              'Text - smajlík');
@define('PLUGIN_MYMOOD_NEW_IMAGE',              'Obrázek (cesta)');

@define('PLUGIN_MYMOOD_ACCOMPLISHED'    , 'dokonalý      ');
@define('PLUGIN_MYMOOD_AGGRAVATED'      , 'pøitì¾ující   ');
@define('PLUGIN_MYMOOD_AMUSED'          , 'pobavený      ');
@define('PLUGIN_MYMOOD_ANGRY'           , 'zuøivý        ');
@define('PLUGIN_MYMOOD_ANNOYED'         , 'rozmrzelý     ');
@define('PLUGIN_MYMOOD_ANXIOUS'         , 'úzkostlivý    ');
@define('PLUGIN_MYMOOD_APATHETIC'       , 'otupìlý       '); 
@define('PLUGIN_MYMOOD_ARTISTIC'        , 'múzou políbený'); 
@define('PLUGIN_MYMOOD_AWAKE'           , 'bdící         '); 
@define('PLUGIN_MYMOOD_BITCHY'          , 'hanebný       '); 
@define('PLUGIN_MYMOOD_BLAH'            , 'kecy          '); 
@define('PLUGIN_MYMOOD_BLANK'           , 'prázdno       '); 
@define('PLUGIN_MYMOOD_BORED'           , 'znudìný       '); 
@define('PLUGIN_MYMOOD_BOUNCY'          , '¾ivý          '); 
@define('PLUGIN_MYMOOD_BUSY'            , 'zaneprázdnìný '); 
@define('PLUGIN_MYMOOD_CALM'            , 'tichý         '); 
@define('PLUGIN_MYMOOD_CHEERFUL'        , 'veselý        '); 
@define('PLUGIN_MYMOOD_CHIPPER'         , 'nastrouhaný   '); 
@define('PLUGIN_MYMOOD_COLD'            , 'chladný       ');
@define('PLUGIN_MYMOOD_COMPLACENT'      , 'uspokojený    ');
@define('PLUGIN_MYMOOD_CONFUSED'        , 'zmatený       ');
@define('PLUGIN_MYMOOD_CONTEMPLATIVE'   , 'zahloubaný    ');
@define('PLUGIN_MYMOOD_CONTENT'         , 'spokojený     ');
@define('PLUGIN_MYMOOD_CRANKY'          , 'potrhlý       ');
@define('PLUGIN_MYMOOD_CRAPPY'          , 'posraný       ');
@define('PLUGIN_MYMOOD_CRAZY'           , 'bláznivý      ');
@define('PLUGIN_MYMOOD_CREATIVE'        , 'nápaditý      ');
@define('PLUGIN_MYMOOD_CRUSHED'         , 'zdrcený       ');
@define('PLUGIN_MYMOOD_CURIOUS'         , 'zvìdavý       ');
@define('PLUGIN_MYMOOD_CYNICAL'         , 'cynický       ');
@define('PLUGIN_MYMOOD_DEPRESSED'       , 'depka         ');
@define('PLUGIN_MYMOOD_DETERMINED'      , 'odhodlaný     ');
@define('PLUGIN_MYMOOD_DEVIOUS'         , 'odolný        ');
@define('PLUGIN_MYMOOD_DIRTY'           , '¹pinavý       ');
@define('PLUGIN_MYMOOD_DISAPPOINTED'    , 'znechucený    ');
@define('PLUGIN_MYMOOD_DISCONTENT'      , 'nespokojený   ');
@define('PLUGIN_MYMOOD_DISTRESSED'      , 'zoufalý       ');
@define('PLUGIN_MYMOOD_DITZY'           , '¹ílený        ');
@define('PLUGIN_MYMOOD_DORKY'           , 'vyma¹tìný     ');
@define('PLUGIN_MYMOOD_DRAINED'         , 'vyèerpaný     ');
@define('PLUGIN_MYMOOD_DRUNK'           , 'opilý         ');
@define('PLUGIN_MYMOOD_ECSTATIC'        , 'nad¹ený       ');
@define('PLUGIN_MYMOOD_EMBARRASSED'     , 'rozpaèitý     ');
@define('PLUGIN_MYMOOD_ENERGETIC'       , 'rázný         ');
@define('PLUGIN_MYMOOD_ENRAGED'         , 'vztelký       ');
@define('PLUGIN_MYMOOD_ENTHRALLED'      , 'fascinovaný   ');
@define('PLUGIN_MYMOOD_ENVIOUS'         , 'závistivý     ');
@define('PLUGIN_MYMOOD_EXANIMATE'       , 'bezduchý      ');
@define('PLUGIN_MYMOOD_EXCITED'         , 'vzru¹ený      ');
@define('PLUGIN_MYMOOD_EXHAUSTED'       , 'u¹tvaný       ');
@define('PLUGIN_MYMOOD_FLIRTY'          , 'flirtující    ');
@define('PLUGIN_MYMOOD_FRUSTRATED'      , 'frustrovaný   ');
@define('PLUGIN_MYMOOD_FULL'            , 'naplnìný      ');
@define('PLUGIN_MYMOOD_GEEKY'           , 'klaunský      ');
@define('PLUGIN_MYMOOD_GIDDY'           , 'spla¹ený      ');
@define('PLUGIN_MYMOOD_GIGGLY'          , 'hihòám se     ');
@define('PLUGIN_MYMOOD_GLOOMY'          , 'skleslý       ');
@define('PLUGIN_MYMOOD_GOOD'            , 'dobrý         ');
@define('PLUGIN_MYMOOD_GRATEFUL'        , 'pøíjemný      ');
@define('PLUGIN_MYMOOD_GROGGY'          , 'grogy         ');
@define('PLUGIN_MYMOOD_GRUMPY'          , 'mrzutý        ');
@define('PLUGIN_MYMOOD_GUILTY'          , 'provinilý     ');
@define('PLUGIN_MYMOOD_HAPPY'           , '¹»astný       ');
@define('PLUGIN_MYMOOD_HIGH'            , 'vysoký        ');
@define('PLUGIN_MYMOOD_HOPEFUL'         , 'slibný        ');
@define('PLUGIN_MYMOOD_HORNY'           , 'nadr¾ený      ');
@define('PLUGIN_MYMOOD_HOT'             , '¾havý         ');
@define('PLUGIN_MYMOOD_HUNGRY'          , 'hladový       ');
@define('PLUGIN_MYMOOD_HYPER'           , 'hyper         ');
@define('PLUGIN_MYMOOD_IMPRESSED'       , 'ohromený      ');
@define('PLUGIN_MYMOOD_INDESCRIBABLE'   , 'nepopsatelný  ');
@define('PLUGIN_MYMOOD_INDIFFERENT'     , 'neutrální     ');
@define('PLUGIN_MYMOOD_INFURIATED'      , 'rozvzteklený  ');
@define('PLUGIN_MYMOOD_INTIMIDATED'     , 'vystra¹ený    ');
@define('PLUGIN_MYMOOD_IRATE'           , 'rozzlobený    ');
@define('PLUGIN_MYMOOD_IRRITATED'       , 'podrá¾dìný    ');
@define('PLUGIN_MYMOOD_JEALOUS'         , '¾árlivý       ');
@define('PLUGIN_MYMOOD_JUBILANT'        , 'vítìzoslavný  ');
@define('PLUGIN_MYMOOD_LAZY'            , 'líný          ');
@define('PLUGIN_MYMOOD_LETHARGIC'       , 'letargie      ');
@define('PLUGIN_MYMOOD_LISTLESS'        , 'mdlý          ');
@define('PLUGIN_MYMOOD_LONELY'          , 'osamìlý       ');
@define('PLUGIN_MYMOOD_LOVED'           , 'milovaný      ');
@define('PLUGIN_MYMOOD_MELANCHOLY'      , 'zádumèivý     ');
@define('PLUGIN_MYMOOD_MELLOW'          , 'zralý         ');
@define('PLUGIN_MYMOOD_MISCHIEVOUS'     , 'uliènický     ');
@define('PLUGIN_MYMOOD_MOODY'           , 'náladový      ');
@define('PLUGIN_MYMOOD_MOROSE'          , 'nevrlý        ');
@define('PLUGIN_MYMOOD_NAUGHTY'         , 'sprostý       ');
@define('PLUGIN_MYMOOD_NAUSEATED'       , 'hnusný        ');
@define('PLUGIN_MYMOOD_NERDY'           , 'blbý          ');
@define('PLUGIN_MYMOOD_NERVOUS'         , 'nervózní      ');
@define('PLUGIN_MYMOOD_NOSTALGIC'       , 'nostalgický   ');
@define('PLUGIN_MYMOOD_NUMB'            , 'prokøehlý     ');
@define('PLUGIN_MYMOOD_OKAY'            , 'oukej         ');
@define('PLUGIN_MYMOOD_OPTIMISTIC'      , 'optimistický  ');
@define('PLUGIN_MYMOOD_PEACEFUL'        , 'poklidný      ');
@define('PLUGIN_MYMOOD_PENSIVE'         , 'zamy¹lený     ');
@define('PLUGIN_MYMOOD_PESSIMISTIC'     , 'pesimistický  ');
@define('PLUGIN_MYMOOD_PISSED_OFF'      , 'obtì¾ovaný    ');
@define('PLUGIN_MYMOOD_PLEASED'         , 'potì¹ený      ');
@define('PLUGIN_MYMOOD_PREDATORY'       , 'krutý         ');
@define('PLUGIN_MYMOOD_PRETTY'          , 'krásný        ');
@define('PLUGIN_MYMOOD_PRODUCTIVE'      , 'výkonný       ');
@define('PLUGIN_MYMOOD_QUIXOTIC'        , 'donkichotský  ');
@define('PLUGIN_MYMOOD_RECUMBENT'       , 'odpoèívající  ');
@define('PLUGIN_MYMOOD_REFRESHED'       , 'obèerstvený   ');
@define('PLUGIN_MYMOOD_REJECTED'        , 'odmítnutý     ');
@define('PLUGIN_MYMOOD_REJUVENATED'     , 'omlazený      ');
@define('PLUGIN_MYMOOD_RELAXED'         , 'odpoèatý      ');
@define('PLUGIN_MYMOOD_RELIEVED'        , 'uvolnìný      ');
@define('PLUGIN_MYMOOD_RESTLESS'        , 'neklidný      ');
@define('PLUGIN_MYMOOD_RUSHED'          , 'uhnaný        ');
@define('PLUGIN_MYMOOD_SAD'             , 'smutný        ');
@define('PLUGIN_MYMOOD_SATISFIED'       , 'spokojený     ');
@define('PLUGIN_MYMOOD_SCARED'          , 'vylekaný      ');
@define('PLUGIN_MYMOOD_SHOCKED'         , '¹okovaný      ');
@define('PLUGIN_MYMOOD_SICK'            , 'nemocný       ');
@define('PLUGIN_MYMOOD_SILLY'           , 'bláznivý      ');
@define('PLUGIN_MYMOOD_SLEEPY'          , 'ospalý        ');
@define('PLUGIN_MYMOOD_SORE'            , 'bolístka      ');
@define('PLUGIN_MYMOOD_STRESSED'        , 'pøetí¾ený     ');
@define('PLUGIN_MYMOOD_SURPRISED'       , 'pøekvapený    ');
@define('PLUGIN_MYMOOD_SYMPATHETIC'     , 'chápavý       ');
@define('PLUGIN_MYMOOD_THANKFUL'        , 'vdìèný        ');
@define('PLUGIN_MYMOOD_THIRSTY'         , '¾íznivý       ');
@define('PLUGIN_MYMOOD_THOUGHTFUL'      , 'peèlivý       ');
@define('PLUGIN_MYMOOD_TIRED'           , 'unavený       ');
@define('PLUGIN_MYMOOD_TOUCHED'         , 'ura¾ený       ');
@define('PLUGIN_MYMOOD_UNCOMFORTABLE'   , 'nepohodlný    ');
@define('PLUGIN_MYMOOD_WEIRD'           , 'tajuplný      ');
@define('PLUGIN_MYMOOD_WORKING'         , 'pracující     ');
@define('PLUGIN_MYMOOD_WORRIED'         , 'ustaraný      ');

?>
