<?php # $Id$

/**
 *  @version $Revision$
 *  @author Translator Name <yourmail@example.com>
 *  EN-Revision: Revision of lang_en.inc.php
 */

@define('PLUGIN_MYMOOD_TITLE', 'My Mood');
@define('PLUGIN_MYMOOD_DESC', 'Allows you to add your current mood or moods to entries.');
@define('PLUGIN_MYMOOD_MOOD_MISSINGDATA', 'Missing user input');
@define('PLUGIN_MYMOOD_MOOD_LIST', 'This is a list of moods available.');
@define('PLUGIN_MYMOOD_MOOD_NAME', 'Mood name');
@define('PLUGIN_MYMOOD_MOOD_IMG', 'Mood image.  (Relative to root, or a full URL)');
@define('PLUGIN_MYMOOD_MOOD_ASCII', 'Ascii Emoticon for the mood.');
@define('PLUGIN_MYMOOD_MOOD_DELETE', 'Delete');
@define('PLUGIN_MYMOOD_CONFIRM_RESET_BUTTON', 'Reset all moods');
@define('PLUGIN_MYMOOD_CONFIRM_RESET', 'Are you sure you want to reset all moods?  This will delete all custom moods, and add only default moods.  \n\nWARNING: This may also cause old entries to display the wrong moods!');

@define('PLUGIN_MYMOOD_INTRO', 'Intro');
@define('PLUGIN_MYMOOD_INTRO_DESC', 'An intro text to your mood, like "My mood:"');
@define('PLUGIN_MYMOOD_OUTRO', 'Outro');
@define('PLUGIN_MYMOOD_OUTRO_DESC', 'An outro text.');
@define('PLUGIN_MYMOOD_TODAY_I_FEEL', 'My mood:');
@define('PLUGIN_MYMOOD_PLACE_FIELD', 'Place near');
@define('PLUGIN_MYMOOD_PLACE_FIELD_DESC', 'Which field to place your mood near');
@define('PLUGIN_MYMOOD_PLACE_FIELD_BODY', 'Body');
@define('PLUGIN_MYMOOD_PLACE_FIELD_AUTHOR', 'Author');
@define('PLUGIN_MYMOOD_PLACE_FIELD_TITLE', 'Title');
@define('PLUGIN_MYMOOD_PLACE_FIELD_FOOTER', 'Footer');
@define('PLUGIN_MYMOOD_PLACE_BEFORE', 'Place before');
@define('PLUGIN_MYMOOD_PLACE_BEFORE_DESC', 'Place your mood before the field you chose?  If no, place it after.');
@define('PLUGIN_MYMOOD_DISPLAY_FORMAT', 'Display Format');
@define('PLUGIN_MYMOOD_DISPLAY_FORMAT_DESC', 'The format of the mood.  You may use {name}, {img}, and {ascii} in any order to control the output of the moods.  This will have no effect if are placing the mood in the title.  You may enter html here.  (Default: {img} {name})');
@define('PLUGIN_MYMOOD_MORE_NEW_MOODS', 'More New Moods');
@define('PLUGIN_MYMOOD_NEW_MOOD', 'New Mood)');
@define('PLUGIN_MYMOOD_NEW_ASCII', 'Ascii');
@define('PLUGIN_MYMOOD_NEW_IMAGE', 'Image (path)');

@define('PLUGIN_MYMOOD_ACCOMPLISHED'    , 'accomplished  ');
@define('PLUGIN_MYMOOD_AGGRAVATED'      , 'aggravated    ');
@define('PLUGIN_MYMOOD_AMUSED'          , 'amused        ');
@define('PLUGIN_MYMOOD_ANGRY'           , 'angry         ');
@define('PLUGIN_MYMOOD_ANNOYED'         , 'annoyed       ');
@define('PLUGIN_MYMOOD_ANXIOUS'         , 'anxious       ');
@define('PLUGIN_MYMOOD_APATHETIC'       , 'apathetic     '); 
@define('PLUGIN_MYMOOD_ARTISTIC'        , 'artistic      '); 
@define('PLUGIN_MYMOOD_AWAKE'           , 'awake         '); 
@define('PLUGIN_MYMOOD_BITCHY'          , 'bitchy        '); 
@define('PLUGIN_MYMOOD_BLAH'            , 'blah          '); 
@define('PLUGIN_MYMOOD_BLANK'           , 'blank         '); 
@define('PLUGIN_MYMOOD_BORED'           , 'bored         '); 
@define('PLUGIN_MYMOOD_BOUNCY'          , 'bouncy        '); 
@define('PLUGIN_MYMOOD_BUSY'            , 'busy          '); 
@define('PLUGIN_MYMOOD_CALM'            , 'calm          '); 
@define('PLUGIN_MYMOOD_CHEERFUL'        , 'cheerful      '); 
@define('PLUGIN_MYMOOD_CHIPPER'         , 'chipper       '); 
@define('PLUGIN_MYMOOD_COLD'            , 'cold          ');
@define('PLUGIN_MYMOOD_COMPLACENT'      , 'complacent    ');
@define('PLUGIN_MYMOOD_CONFUSED'        , 'confused      ');
@define('PLUGIN_MYMOOD_CONTEMPLATIVE'   , 'contemplative ');
@define('PLUGIN_MYMOOD_CONTENT'         , 'content       ');
@define('PLUGIN_MYMOOD_CRANKY'          , 'cranky        ');
@define('PLUGIN_MYMOOD_CRAPPY'          , 'crappy        ');
@define('PLUGIN_MYMOOD_CRAZY'           , 'crazy         ');
@define('PLUGIN_MYMOOD_CREATIVE'        , 'creative      ');
@define('PLUGIN_MYMOOD_CRUSHED'         , 'crushed       ');
@define('PLUGIN_MYMOOD_CURIOUS'         , 'curious       ');
@define('PLUGIN_MYMOOD_CYNICAL'         , 'cynical       ');
@define('PLUGIN_MYMOOD_DEPRESSED'       , 'depressed     ');
@define('PLUGIN_MYMOOD_DETERMINED'      , 'determined    ');
@define('PLUGIN_MYMOOD_DEVIOUS'         , 'devious       ');
@define('PLUGIN_MYMOOD_DIRTY'           , 'dirty         ');
@define('PLUGIN_MYMOOD_DISAPPOINTED'    , 'disappointed  ');
@define('PLUGIN_MYMOOD_DISCONTENT'      , 'discontent    ');
@define('PLUGIN_MYMOOD_DISTRESSED'      , 'distressed    ');
@define('PLUGIN_MYMOOD_DITZY'           , 'ditzy         ');
@define('PLUGIN_MYMOOD_DORKY'           , 'dorky         ');
@define('PLUGIN_MYMOOD_DRAINED'         , 'drained       ');
@define('PLUGIN_MYMOOD_DRUNK'           , 'drunk         ');
@define('PLUGIN_MYMOOD_ECSTATIC'        , 'ecstatic      ');
@define('PLUGIN_MYMOOD_EMBARRASSED'     , 'embarrassed   ');
@define('PLUGIN_MYMOOD_ENERGETIC'       , 'energetic     ');
@define('PLUGIN_MYMOOD_ENRAGED'         , 'enraged       ');
@define('PLUGIN_MYMOOD_ENTHRALLED'      , 'enthralled    ');
@define('PLUGIN_MYMOOD_ENVIOUS'         , 'envious       ');
@define('PLUGIN_MYMOOD_EXANIMATE'       , 'exanimate     ');
@define('PLUGIN_MYMOOD_EXCITED'         , 'excited       ');
@define('PLUGIN_MYMOOD_EXHAUSTED'       , 'exhausted     ');
@define('PLUGIN_MYMOOD_FLIRTY'          , 'flirty        ');
@define('PLUGIN_MYMOOD_FRUSTRATED'      , 'frustrated    ');
@define('PLUGIN_MYMOOD_FULL'            , 'full          ');
@define('PLUGIN_MYMOOD_GEEKY'           , 'geeky         ');
@define('PLUGIN_MYMOOD_GIDDY'           , 'giddy         ');
@define('PLUGIN_MYMOOD_GIGGLY'          , 'giggly        ');
@define('PLUGIN_MYMOOD_GLOOMY'          , 'gloomy        ');
@define('PLUGIN_MYMOOD_GOOD'            , 'good          ');
@define('PLUGIN_MYMOOD_GRATEFUL'        , 'grateful      ');
@define('PLUGIN_MYMOOD_GROGGY'          , 'groggy        ');
@define('PLUGIN_MYMOOD_GRUMPY'          , 'grumpy        ');
@define('PLUGIN_MYMOOD_GUILTY'          , 'guilty        ');
@define('PLUGIN_MYMOOD_HAPPY'           , 'happy         ');
@define('PLUGIN_MYMOOD_HIGH'            , 'high          ');
@define('PLUGIN_MYMOOD_HOPEFUL'         , 'hopeful       ');
@define('PLUGIN_MYMOOD_HORNY'           , 'horny         ');
@define('PLUGIN_MYMOOD_HOT'             , 'hot           ');
@define('PLUGIN_MYMOOD_HUNGRY'          , 'hungry        ');
@define('PLUGIN_MYMOOD_HYPER'           , 'hyper         ');
@define('PLUGIN_MYMOOD_IMPRESSED'       , 'impressed     ');
@define('PLUGIN_MYMOOD_INDESCRIBABLE'   , 'indescribable ');
@define('PLUGIN_MYMOOD_INDIFFERENT'     , 'indifferent   ');
@define('PLUGIN_MYMOOD_INFURIATED'      , 'infuriated    ');
@define('PLUGIN_MYMOOD_INTIMIDATED'     , 'intimidated   ');
@define('PLUGIN_MYMOOD_IRATE'           , 'irate         ');
@define('PLUGIN_MYMOOD_IRRITATED'       , 'irritated     ');
@define('PLUGIN_MYMOOD_JEALOUS'         , 'jealous       ');
@define('PLUGIN_MYMOOD_JUBILANT'        , 'jubilant      ');
@define('PLUGIN_MYMOOD_LAZY'            , 'lazy          ');
@define('PLUGIN_MYMOOD_LETHARGIC'       , 'lethargic     ');
@define('PLUGIN_MYMOOD_LISTLESS'        , 'listless      ');
@define('PLUGIN_MYMOOD_LONELY'          , 'lonely        ');
@define('PLUGIN_MYMOOD_LOVED'           , 'loved         ');
@define('PLUGIN_MYMOOD_MELANCHOLY'      , 'melancholy    ');
@define('PLUGIN_MYMOOD_MELLOW'          , 'mellow        ');
@define('PLUGIN_MYMOOD_MISCHIEVOUS'     , 'mischievous   ');
@define('PLUGIN_MYMOOD_MOODY'           , 'moody         ');
@define('PLUGIN_MYMOOD_MOROSE'          , 'morose        ');
@define('PLUGIN_MYMOOD_NAUGHTY'         , 'naughty       ');
@define('PLUGIN_MYMOOD_NAUSEATED'       , 'nauseated     ');
@define('PLUGIN_MYMOOD_NERDY'           , 'nerdy         ');
@define('PLUGIN_MYMOOD_NERVOUS'         , 'nervous       ');
@define('PLUGIN_MYMOOD_NOSTALGIC'       , 'nostalgic     ');
@define('PLUGIN_MYMOOD_NUMB'            , 'numb          ');
@define('PLUGIN_MYMOOD_OKAY'            , 'okay          ');
@define('PLUGIN_MYMOOD_OPTIMISTIC'      , 'optimistic    ');
@define('PLUGIN_MYMOOD_PEACEFUL'        , 'peaceful      ');
@define('PLUGIN_MYMOOD_PENSIVE'         , 'pensive       ');
@define('PLUGIN_MYMOOD_PESSIMISTIC'     , 'pessimistic   ');
@define('PLUGIN_MYMOOD_PISSED_OFF'      , 'pissed off    ');
@define('PLUGIN_MYMOOD_PLEASED'         , 'pleased       ');
@define('PLUGIN_MYMOOD_PREDATORY'       , 'predatory     ');
@define('PLUGIN_MYMOOD_PRETTY'          , 'pretty        ');
@define('PLUGIN_MYMOOD_PRODUCTIVE'      , 'productive    ');
@define('PLUGIN_MYMOOD_QUIXOTIC'        , 'quixotic      ');
@define('PLUGIN_MYMOOD_RECUMBENT'       , 'recumbent     ');
@define('PLUGIN_MYMOOD_REFRESHED'       , 'refreshed     ');
@define('PLUGIN_MYMOOD_REJECTED'        , 'rejected      ');
@define('PLUGIN_MYMOOD_REJUVENATED'     , 'rejuvenated   ');
@define('PLUGIN_MYMOOD_RELAXED'         , 'relaxed       ');
@define('PLUGIN_MYMOOD_RELIEVED'        , 'relieved      ');
@define('PLUGIN_MYMOOD_RESTLESS'        , 'restless      ');
@define('PLUGIN_MYMOOD_RUSHED'          , 'rushed        ');
@define('PLUGIN_MYMOOD_SAD'             , 'sad           ');
@define('PLUGIN_MYMOOD_SATISFIED'       , 'satisfied     ');
@define('PLUGIN_MYMOOD_SCARED'          , 'scared        ');
@define('PLUGIN_MYMOOD_SHOCKED'         , 'shocked       ');
@define('PLUGIN_MYMOOD_SICK'            , 'sick          ');
@define('PLUGIN_MYMOOD_SILLY'           , 'silly         ');
@define('PLUGIN_MYMOOD_SLEEPY'          , 'sleepy        ');
@define('PLUGIN_MYMOOD_SORE'            , 'sore          ');
@define('PLUGIN_MYMOOD_STRESSED'        , 'stressed      ');
@define('PLUGIN_MYMOOD_SURPRISED'       , 'surprised     ');
@define('PLUGIN_MYMOOD_SYMPATHETIC'     , 'sympathetic   ');
@define('PLUGIN_MYMOOD_THANKFUL'        , 'thankful      ');
@define('PLUGIN_MYMOOD_THIRSTY'         , 'thirsty       ');
@define('PLUGIN_MYMOOD_THOUGHTFUL'      , 'thoughtful    ');
@define('PLUGIN_MYMOOD_TIRED'           , 'tired         ');
@define('PLUGIN_MYMOOD_TOUCHED'         , 'touched       ');
@define('PLUGIN_MYMOOD_UNCOMFORTABLE'   , 'uncomfortable ');
@define('PLUGIN_MYMOOD_WEIRD'           , 'weird         ');
@define('PLUGIN_MYMOOD_WORKING'         , 'working       ');
@define('PLUGIN_MYMOOD_WORRIED'         , 'worried       ');

?>
