<?php

@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_NAME', "多合一无障碍™");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_DESC',  "多合一无障碍™ 小部件改进了网站 ADA 合规性和浏览器体验，符合 ADA、WCAG 2.1 和 2.2、第 508 条、澳大利亚 DDA、欧洲 EAA EN 301 549、英国平等法案 (EA)、以色列标准 5568、加利福尼亚州 Unruh、安大略省 AODA、加拿大 ACA、德国 BITV 、法国 RGAA、巴西包容性法 (LBI 13.146/2015)、西班牙 UNE 139803:2012、JIS X 8341（日本）、意大利斯坦卡法案和瑞士 DDA 标准。多合一辅助功能小组件符合 GDPR、COPPA 法规.");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_AUTHOR' ,   "拉杰什·比马尼");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_LICENCE_KEY' ,   "许可证号 :");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_COLOR' ,   "颜色 :");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_ICON_POSITION' ,   "图标位置 :");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_ICON_POSITION_DESCRIPTION' ,"您希望将辅助功能图标放置在网站的什么位置？");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_ICON_TYPE' ,   "选择图标类型 :");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_ICON_SIZE' ,   "选择图标大小 :");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_ACCESSIBILITY' ,   "无障碍");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_WHEELCHAIR' ,   "轮椅");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_LOWVISION' ,   "低视力");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_AIOA_BIG_ICON' ,   "大的");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_AIOA_MEDIUM_ICON' ,   "中等的");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_AIOA_ICON' ,   "默认");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_AIOA_SMALL_ICON' ,   "小的");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_AIOA_EXTRA_SMALL_ICON' ,   "特小号");

?>
