<?php

@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_NAME', "All in One Accessibility™");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_DESC',  "All in One Accessibility™ widget improves website ADA compliance and browser experience for ADA, WCAG 2.1 & 2.2, Section 508, Australian DDA, European EAA EN 301 549, UK Equality Act (EA), Israeli Standard 5568, California Unruh, Ontario AODA, Canada ACA, German BITV, France RGAA, Brazilian Inclusion Law (LBI 13.146/2015), Spain UNE 139803:2012, JIS X 8341 (Japan), Italian Stanca Act and Switzerland DDA Standards. All in One Accessibility Widget complies with GDPR, COPPA regulations.");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_AUTHOR' ,   "Rajesh Bhimani");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_LICENCE_KEY' ,   "License Key :");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_COLOR' ,   "Color :");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_ICON_POSITION' ,   "Icon Position :");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_ICON_POSITION_TOP_LEFT' ,   "Top Left");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_ICON_POSITION_TOP_CENTER' ,   "Top Center");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_ICON_POSITION_TOP_RIGHT' ,   "Top Right");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_ICON_POSITION_BOTTOM_LEFT' ,   "Bottom left");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_ICON_POSITION_BOTTOM_RIGHT' ,   "Bottom Right");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_ICON_POSITION_BOTTOM_CENTER' ,   "Bottom Center");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_ICON_POSITION_MIDDLE_LEFT' ,   "Middle left");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_ICON_POSITION_MIDDLE_RIGHT' ,   "Middle Right");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_ICON_POSITION_LABEL' ,   "Where would you like to place the accessibility icon on your site?");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_ICON_TYPE' ,   "Select icon type :");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_ICON_SIZE' ,   "Select icon size :");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_ACCESSIBILITY' ,   "Accessibility");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_WHEELCHAIR' ,   "Wheelchair");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_LOWVISION' ,   "Low Vision");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_AIOA_BIG_ICON' ,   "Big");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_AIOA_MEDIUM_ICON' ,   "Medium");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_AIOA_ICON' ,   "Default");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_AIOA_SMALL_ICON' ,   "Small");
@define('PLUGIN_EVENT_ALLINONEACCESSIBILITY_AIOA_EXTRA_SMALL_ICON' ,   "Extra Small");

?>
