<?php
@define('PLUGIN_EVENT_OSM_NAME', 'OpenStreetMap Integration');
@define('PLUGIN_EVENT_OSM_DESCRIPTION', 'Bietet eine interaktive Karte für *.gpx Uploads und Blogs mit Geo-Daten');
@define('PLUGIN_EVENT_OSM_NOT_SHOWN', 'Wird nicht auf der Webseite angezeigt');
@define('PLUGIN_EVENT_STATIC_OSM_NAME', 'OpenStreetMap Statische Dateien');
@define('PLUGIN_EVENT_STATIC_OSM_DESCRIPTION', 'Fügt Scripte und Stylesheets für OpenStreetMap ein');
@define('PLUGIN_EVENT_STATIC_OSM_COMPRESS_GPX', 'GPX-Dateien komprimieren');
@define('PLUGIN_EVENT_STATIC_OSM_COMPRESS_GPX_DESCRIPTION', 'Entfernt alle nicht benötigten Daten aus den GPX-Dateien beim Upload');
@define('PLUGIN_EVENT_OSM_CATEGORY', 'Kategorie');
@define('PLUGIN_EVENT_OSM_CATEGORY_DESCRIPTION', 'Karte wird für diese Kategorie angezeigt');
@define('PLUGIN_EVENT_OSM_CATEGORY_WITHOUT', 'Ohne');
@define('PLUGIN_EVENT_OSM_CATEGORY_ANY', 'Beliebig');
@define('PLUGIN_EVENT_OSM_PATH', 'Pfad');
@define('PLUGIN_EVENT_OSM_PATH_DESCRIPTION', 'Pfad(e) für GPX-Dateien, getrennt durch Zeilenumbruch');
@define('PLUGIN_EVENT_OSM_LAT', 'Breitengrad (Lat.)');
@define('PLUGIN_EVENT_OSM_LAT_DESCRIPTION', 'Breitengrad für die Mitte der Karte');
@define('PLUGIN_EVENT_OSM_LONG', 'Längengrad (Lon.)');
@define('PLUGIN_EVENT_OSM_LONG_DESCRIPTION', 'Längengrad für die Mitte der Karte');
@define('PLUGIN_EVENT_OSM_ZOOM', 'Zoom');
@define('PLUGIN_EVENT_OSM_ZOOM_DESCRIPTION', 'Zoom Level der Karte');
@define('PLUGIN_EVENT_OSM_HEIGHT', 'Kartenhöhe');
@define('PLUGIN_EVENT_OSM_HEIGHT_DESCRIPTION', 'Die Höhe der Karte');
