<?php
@define('PLUGIN_SOCIALBOOKMARKS_N', 'Social Bookmarks Plugin');
@define('PLUGIN_SOCIALBOOKMARKS_D', 'Ein Plugin, um Lesezeichen mithilfe eines RSS-Feeds eines social bookmarks-Dienstes (del.icio.us, ma.gnolia, furl.net, linkroll, Mister Wong) anzuzeigen.');
@define('PLUGIN_SOCIALBOOKMARKS_TITLE_N', 'Titel');
@define('PLUGIN_SOCIALBOOKMARKS_TITLE_D', 'Titel, der in der Seitenleiste als Überschrift angezeigt wird (leer lassen, um Service-Name anzuzeigen).');
@define('PLUGIN_SOCIALBOOKMARKS_SOCIALBOOKMARKSSERVICE_N', 'Service');
@define('PLUGIN_SOCIALBOOKMARKS_SOCIALBOOKMARKSSERVICE_D', 'Welcher social bookmarks-Dienst soll benutzt werden?');
@define('PLUGIN_SOCIALBOOKMARKS_USERNAME_N', 'Benutzername');
@define('PLUGIN_SOCIALBOOKMARKS_USERNAME_D', 'Mein Benutzername für den social bookmarks-Dienst.');
@define('PLUGIN_SOCIALBOOKMARKS_DISPLAYNUMBER_N', 'Anzahl der darzustellenden Links');
@define('PLUGIN_SOCIALBOOKMARKS_DISPLAYNUMBER_D', 'Wie viele Bookmarks sollen dargestellt werden (Standard ist die maximale Feed-Größe, 30)');
@define('PLUGIN_SOCIALBOOKMARKS_CACHETIME_N', 'Wann soll der Feed aktualisiert werden?');
@define('PLUGIN_SOCIALBOOKMARKS_CACHETIME_D', 'Der Inhalt des Feeds wird in einem Cache gespeichert, der aktualisiert wird, sobald er älter als X Stunden ist (Standard: 1).');
@define('PLUGIN_SOCIALBOOKMARKS_MORELINK_N', 'Zeig "mehr"-Verknüpfung');
@define('PLUGIN_SOCIALBOOKMARKS_MORELINK_D', 'Zeige Verknüpfung zu meiner social bookmarks-Seite.');
@define('PLUGIN_SOCIALBOOKMARKS_MORELINK', 'Mehr');
@define('PLUGIN_SOCIALBOOKMARKS_DISPLAYTAGS_N', 'Tags anzeigen?');
@define('PLUGIN_SOCIALBOOKMARKS_DISPLAYTAGS_D', 'Zeigt zu jedem Lesezeichen die ggf. gespeicherten Stichworte an und erlaubt, im Weblog nach diesem Tags zu suchen. (Möglich nur für del.icio.us, ma.gnolia.com und furl.net).');
@define('PLUGIN_SOCIALBOOKMARKS_DISPLAYTHUMBS_N', 'Vorschaugrafiken anzeigen (ma.gnolia)?');
@define('PLUGIN_SOCIALBOOKMARKS_DISPLAYTHUMBS_D', 'Manche social bookmarks-Dienste (zurzeit nur ma.gnolia) betten kleine Vorschaugrafiken (thumbnails) in ihre RSS-Feeds ein. Diese können anstelle der Lesezeichen-Namen angezeigt werden.');
@define('PLUGIN_SOCIALBOOKMARKS_ADDPARAMS_N', 'Zusätzliche Parameter für die Einstellung "Meine Tagcloud (del.icio.us)"');
@define('PLUGIN_SOCIALBOOKMARKS_ADDPARAMS_D', 'Diese Paramter sind nur für del.icio.us\' Javascript Tagcloud-Funktion wirksam. Mehr Informationen über die Anpassung der Tagcloud ist in der del.icio.us tagrool help (http://del.icio.us/help/tagrolls) zu finden.');
@define('PLUGIN_SOCIALBOOKMARKS_SPECIALFEATURES_N', 'Feed-Einstellungen');
@define('PLUGIN_SOCIALBOOKMARKS_SPECIALFEATURES_D', 'Verschiedene Arten von RSS-Feeds können abgerufen werden.');
@define('PLUGIN_SOCIALBOOKMARKS_SPECIALFEATURES_USR_RECENT', 'Meine neuesten Lesezeichen');
@define('PLUGIN_SOCIALBOOKMARKS_SPECIALFEATURES_GEN_RECENT', 'Neueste Lesezeichen aller User');
@define('PLUGIN_SOCIALBOOKMARKS_SPECIALFEATURES_GEN_POPULAR', 'Populärste Lesezeichen der letzten 24 Stunden');
@define('PLUGIN_SOCIALBOOKMARKS_SPECIALFEATURES_USR_JS_TAGCLOUD', 'Meine Tagcloud (del.icio.us)');
@define('PLUGIN_SOCIALBOOKMARKS_EXPLAIN', '<h3>Was macht dieses Plugin?</h3><p>Lesezeichen helfen eine einmal gefundene Seite auch ohne Suchmaschine wiederzufinden. Erfahrene Internetanwender sammeln Lesezeichen und kommen so häufig auf tausende von Einträgen. Soziale Lesezeichen oder auch social bookmarks werden die Lesezeichen genannt, die öffentlich verwaltet werden. Neben der Webseite werden die Lesezeichen oft als abonnierbare Liste (meistens als RSS-Feed) publiziert.</p><p>Mithilfe dieses Plugins lassen sich kürzlich gespeicherte persönliche Lesezeichen von einem Social bookmarks-Dienst einfach im Blog anzeigen.</p>');
?>