<?php

	@define('PLUGIN_SIDEBAR_WEATHER_NAME', 'Clima');
   	@define('PLUGIN_SIDEBAR_WEATHER_DESC', 'Muestra el Clima actual en un bloque lateral.');
   	@define('PLUGIN_SIDEBAR_WEATHER_TITLE', 'Encabezado');
   	@define('PLUGIN_SIDEBAR_WEATHER_TITLE_BLAHBLAH', 'Encabezado del bloque lateral');
   	@define('PLUGIN_SIDEBAR_WEATHER_METAR', 'METAR del Clima, por ejemplo SCIE');
   	@define('PLUGIN_SIDEBAR_WEATHER_METAR_BLAHBLAH', 'Busca tu fuente METAR del Clima en http://weather.noaa.gov/');
   	@define('PLUGIN_SIDEBAR_WEATHER_TIMEZONE', 'Tu Zona Horaria');
   	@define('PLUGIN_SIDEBAR_WEATHER_TIMEZONE_BLAHBLAH', 'La Zona Horaria debe estar en relación con GMT (ej. +10 o -5)');
   	@define('PLUGIN_SIDEBAR_WEATHER_UNITS','Unidades de Medida');
   	@define('PLUGIN_SIDEBAR_WEATHER_UNITS_BLAHBLAH','Selecciona las Unidades de Medida a utilizar');
   	@define('PLUGIN_SIDEBAR_WEATHER_UNITS_NAME_METRIC', 'Metricas');
	@define('PLUGIN_SIDEBAR_WEATHER_UNITS_NAME_IMPERIAL', 'Imperial/Americana');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_UPDATE', 'Última Actualización:');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_WINDDIRECTION', 'Dirección del Viento:');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_VISIBILITY', 'Visibilidad:');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_CLOUDS_AMOUNT', 'Nublado:');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_CLOUDS_HEIGHT', 'Nubes en Altura:');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_TEMPERATURE', 'Temperatura:');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_FELT_TEMPERATURE', 'Sensación Térmica:');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_HUMIDITY', 'Humedad:');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_PRESSURE', 'Presión:');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_RAIN', 'Lluvia:');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_S', 'Sur');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_SE', 'Sureste');
  	@define('PLUGIN_SIDEBAR_WEATHER_DATA_SW', 'Suroeste');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_SSW', 'Sur/Suroeste');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_SSE', 'Sur/Sureste');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_E', 'Este');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_ESE', 'Este/Sureste');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_ENE', 'Este/Noreste');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_N', 'Norte');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_NW', 'Noroeste');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_NE', 'Noreste');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_NNW', 'Norte/Noroeste');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_NNE', 'Norte/Noreste');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_W', 'Oeste');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_WNW', 'Oeste/Noroeste');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_WSW', 'Oeste/Suroeste');
   	@define('PLUGIN_SIDEBAR_WEATHER_DATA_V', 'Variable');
   	@define('PLUGIN_SIDEBAR_WEATHER_CACHE_ENTRIES', 'Guardar cache de la información del Clima?');
   	@define('PLUGIN_SIDEBAR_WEATHER_CACHE_ENTRIES_DESC', 'Debes tener PEAR:Cache instalado.');
   	@define('PLUGIN_SIDEBAR_WEATHER_CACHE_DIRECTORY', 'Directorio para la información cache:');
   	@define('PLUGIN_SIDEBAR_WEATHER_CACHE_DIRECTORY_DESC', 'El Servidor debe tener permisos de lectura y escritura sobre este directorio.');
