<?php
        @define('PLUGIN_SIDEBAR_HIDER_NAME', 'Seitenleisten ein/ausklappbar machen');
        @define('PLUGIN_SIDEBAR_HIDER_DESC', 'Verkleinert Seitenleisten-Elemente auf ihren Titel und ermöglicht das individuelle Ausklappen. Zusätzliche Konfiguration siehe Einträge -> Seitenleisten verwalten in der Administrationsoberfläche.');
        @define('PLUGIN_SIDEBAR_HIDER_STYLE_SIDEBAR', 'CSS-Style der versteckten Seitenleite');
        @define('PLUGIN_SIDEBAR_HIDER_STYLE_SIDEBAR_DESC', 'CSS-Code der auf jedes Seitenleisten-Element angewendet wird, wenn die Seitenleiste versteckt wird (z.B. padding-bottom entfernen).');
        @define('PLUGIN_SIDEBAR_HIDER_STYLE_TITLE', 'CSS-Style des Titels einer versteckten Seitenleiste');
        @define('PLUGIN_SIDEBAR_HIDER_STYLE_TITLE_DESC', 'CSS-Code der auf jedes Seitenleisten-Titel-Element angewendet wird, wenn die Seitenleiste versteckt wird (z.B. border-bottom entfernen).');
        @define('PLUGIN_SIDEBAR_HIDER_STYLE_LINK', 'CSS-Style des Verstecken-Links');
        @define('PLUGIN_SIDEBAR_HIDER_STYLE_LINK_DESC', 'CSS-Code der auf den Link zum Verstecken angewendet wird.');
        @define('PLUGIN_SIDEBAR_HIDER_LINK_VISIBLE', 'HTML für den Anzeigen-Links');
        @define('PLUGIN_SIDEBAR_HIDER_LINK_VISIBLE_DESC', 'HTML-Code für den Link zum Anzeigen bei versteckter Seitenleiste. (z.B. ein Bild)');
        @define('PLUGIN_SIDEBAR_HIDER_LINK_HIDDEN', 'HTML für den Verstecken-Link');        
        @define('PLUGIN_SIDEBAR_HIDER_LINK_HIDDEN_DESC', 'HTML-Code für den Link zum Verstecken bei angezeigter Seitenleiste. (z.B. ein Bild)');
        @define('PLUGIN_SIDEBAR_HIDER_ADMINLINK', 'Seitenleisten verwalten');
        @define('PLUGIN_SIDEBAR_HIDER_CONF', 'Konfiguration der ein/ausklappbaren Seitenleisten');
        @define('PLUGIN_SIDEBAR_HIDER_CONF_DESC', 'Hinweis: Dieses Plugin versteckt die Seitenleisten anhand der Position einer Seitenleiste. Änderungen in der Plugin-Konfiguration bei der Positionierung wirken sich an dieser Stelle nicht direkt aus und müssen manuell aktualisiert werden. Die Einschränkung der Ansichtsrechte funktionieren nur ab Serendipity 0.9.');
        @define('PLUGIN_SIDEBAR_HIDER_CONF_HIDDEN', 'Versteckt:');
        @define('PLUGIN_SIDEBAR_HIDER_CONF_MEMBERS', 'Nur Mitglieder:');
        @define('PLUGIN_SIDEBAR_HIDER_CONF_MYSELF', 'Nur ich:');
        @define('PLUGIN_SIDEBAR_HIDER_CONF_CATEGORIES', 'Nur Kategorien:');
        @define('PLUGIN_SIDEBAR_HIDER_CONF_EVERYONE', 'Jeder Besucher:');
