<?php # 

/**
 *  @version $Revision$
 *  @author Translator Luis Sieira García <jaimito.hendrix@gmail.com>
 *  EN-Revision: Revision of lang_en.inc.php
 */

@define('PLUGIN_EVENT_AMAZONCHOOSER_TITLE', 'Botón Amazon Media');
@define('PLUGIN_EVENT_AMAZONCHOOSER_DESC', 'Incluye un botón para permitir la búsqueda en Amazon.com y la inclusión de los resultados en tus entradas');
@define('PLUGIN_EVENT_AMAZONCHOOSER_MEDIA_BUTTON', 'Amazon Media');
@define('PLUGIN_EVENT_AMAZONCHOOSER_DEV_TOKEN', 'Número de clave de acceso de desarrollador');
@define('PLUGIN_EVENT_AMAZONCHOOSER_DEV_TOKEN_DESC', 'Debes registrarte en Amazon web services para recibir esto');
@define('PLUGIN_EVENT_AMAZONCHOOSER_DEV_SECRET','Clave de acceso secreta de desarrollador.');
@define('PLUGIN_EVENT_AMAZONCHOOSER_DEV_SECRET_DESC','La clave secreta de tu cuenta de Amazon Web Services');
@define('PLUGIN_EVENT_AMAZONCHOOSER_ASSOCIATE_ID', 'ID de seguimiento de afiliados de Amazon');
@define('PLUGIN_EVENT_AMAZONCHOOSER_ASSOCIATE_ID_DESC', 'Tu ID de afliado de Amazon');
@define('PLUGIN_EVENT_AMAZONCHOOSER_SERVER', 'Servidor por defecto');
@define('PLUGIN_EVENT_AMAZONCHOOSER_SERVER_DESC', 'Servidor de Amazon que quieres usar para localización');
@define('PLUGIN_EVENT_AMAZONCHOOSER_GERMANY', 'Alemania');
@define('PLUGIN_EVENT_AMAZONCHOOSER_JAPAN', 'Japón');
@define('PLUGIN_EVENT_AMAZONCHOOSER_UK', 'Reino Unido');
@define('PLUGIN_EVENT_AMAZONCHOOSER_US', 'Estados Unidos');
@define('PLUGIN_EVENT_AMAZONCHOOSER_CA', 'Canadá');
@define('PLUGIN_EVENT_AMAZONCHOOSER_FR', 'Francia');
@define('PLUGIN_EVENT_AMAZONCHOOSER_CN', 'China');
@define('PLUGIN_EVENT_AMAZONCHOOSER_IT', 'Itala');
@define('PLUGIN_EVENT_AMAZONCHOOSER_ES', 'España');
@define('PLUGIN_EVENT_AMAZONCHOOSER_SEARCH', 'Buscar');
@define('PLUGIN_EVENT_AMAZONCHOOSER_SEARCH_DESC', 'Introduce un término de búsqueda:');
@define('PLUGIN_EVENT_AMAZONCHOOSER_CLICK', 'Haz click en el item que estás buscando:');
@define('PLUGIN_EVENT_AMAZONCHOOSER_CHOSE', 'Elegiste ');
@define('PLUGIN_EVENT_AMAZONCHOOSER_AUTHOR', 'Autor:');
@define('PLUGIN_EVENT_AMAZONCHOOSER_RELEASED', 'Publicado');
@define('PLUGIN_EVENT_AMAZONCHOOSER_MANUFACTURER', 'Fabricante');
@define('PLUGIN_EVENT_AMAZONCHOOSER_DISTRIBUTOR', 'Distribuidor');
@define('PLUGIN_EVENT_AMAZONCHOOSER_STARRING', 'Colaboradores');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PUBLISHER', 'Publicador');
@define('PLUGIN_EVENT_AMAZONCHOOSER_ARTISTS', 'Artista');
@define('PLUGIN_EVENT_AMAZONCHOOSER_DIRECTOR', 'Director');
@define('PLUGIN_EVENT_AMAZONCHOOSER_NUMPAGES', 'Número de páginas');
@define('PLUGIN_EVENT_AMAZONCHOOSER_ISBN', 'ISBN');
@define('PLUGIN_EVENT_AMAZONCHOOSER_RUNNING', 'Tiempo en ejecución');
@define('PLUGIN_EVENT_AMAZONCHOOSER_FORMAT', 'Formato');
@define('PLUGIN_EVENT_AMAZONCHOOSER_EAN', 'EAN');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PRODUCTTITLE','Título');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PLATFORM','Plataforma');
@define('PLUGIN_EVENT_AMAZONCHOOSER_GENRE','Género');
@define('PLUGIN_EVENT_AMAZONCHOOSER_ESRBAGERATING','Rating ESRB');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PRICE','Precio');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PUBLISHED','Publicado');
@define('PLUGIN_EVENT_AMAZONCHOOSER_DISTINCTURL','Más información');
@define('PLUGIN_EVENT_AMAZONCHOOSER_TECHDETAILS','Detalles técnicos');
@define('PLUGIN_EVENT_AMAZONCHOOSER_CUSTOMERREVIEWS','Ver críticas de los usuarios');
@define('PLUGIN_EVENT_AMAZONCHOOSER_ALLOFFERS','Ver todas las ofertas');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PRODUCTGROUP','Tipo de producto:');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PRODUCTLANGUAGE','Idioma');
@define('PLUGIN_EVENT_AMAZONCHOOSER_AUDIENCERATING','Calificación');
@define('PLUGIN_EVENT_AMAZONCHOOSER_NEW','nuevo');
@define('PLUGIN_EVENT_AMAZONCHOOSER_USED','usado');
@define('PLUGIN_EVENT_AMAZONCHOOSER_COLLECTABLE','coleccionable');
@define('PLUGIN_EVENT_AMAZONCHOOSER_REFURBISHED','restaurado');
@define('PLUGIN_EVENT_AMAZONCHOOSER_FROM','desde');
@define('PLUGIN_EVENT_AMAZONCHOOSER_NOASIN','No se especificó ASIN en la búsqueda. Parece ser un problema en la postdata almacenada.');
@define('PLUGIN_EVENT_AMAZONCHOOSER_BRAND','Marca');
@define('PLUGIN_EVENT_AMAZONCHOOSER_MODEL','Modelo');
@define('PLUGIN_EVENT_AMAZONCHOOSER_NUMDISKS','Número de discos');
@define('PLUGIN_EVENT_AMAZONCHOOSER_FEATURE','Características');
@define('PLUGIN_EVENT_AMAZONCHOOSER_DISPLAYING','Mostrando');
@define('PLUGIN_EVENT_AMAZONCHOOSER_OF','de');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PAGE','página');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PAGES','páginas');
@define('PLUGIN_EVENT_AMAZONCHOOSER_ITEMS','items');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PAGELIMIT','Sólo 400 páginas visibles');
@define('PLUGIN_EVENT_AMAZONCHOOSER_ASOF','Información lo más precisa de');
@define('PLUGIN_EVENT_AMAZONCHOOSER_APPAREL','Ropa');
@define('PLUGIN_EVENT_AMAZONCHOOSER_AUTO','Automoción');
@define('PLUGIN_EVENT_AMAZONCHOOSER_BABY','Babé');
@define('PLUGIN_EVENT_AMAZONCHOOSER_BEAUTY','Belleza');
@define('PLUGIN_EVENT_AMAZONCHOOSER_BOOKS','Libros');
@define('PLUGIN_EVENT_AMAZONCHOOSER_CLASSICALMUSIC','Música clásica');
@define('PLUGIN_EVENT_AMAZONCHOOSER_DIGITALMUSIC','Música digital');
@define('PLUGIN_EVENT_AMAZONCHOOSER_DVD','DVD');
@define('PLUGIN_EVENT_AMAZONCHOOSER_ELECTRONICS','Electrónica');
@define('PLUGIN_EVENT_AMAZONCHOOSER_FOREIGNBOOKS','Libros en idiomas extranjeros');
@define('PLUGIN_EVENT_AMAZONCHOOSER_GORMETFOOD','Comida Gourmet');
@define('PLUGIN_EVENT_AMAZONCHOOSER_GROCERY','Alimentación');
@define('PLUGIN_EVENT_AMAZONCHOOSER_HEALTH','Salud/Cuidado personal');
@define('PLUGIN_EVENT_AMAZONCHOOSER_HOBBIES','Hobbies');
@define('PLUGIN_EVENT_AMAZONCHOOSER_HOMEGARDEN','Casa/Jardín');
@define('PLUGIN_EVENT_AMAZONCHOOSER_HOMEIMPROVE','Bricolaje');
@define('PLUGIN_EVENT_AMAZONCHOOSER_INDUSTRIAL','Industrial');
@define('PLUGIN_EVENT_AMAZONCHOOSER_JEWELRY','Joyería');
@define('PLUGIN_EVENT_AMAZONCHOOSER_KINDLESTORE','Tienda Kindle');
@define('PLUGIN_EVENT_AMAZONCHOOSER_KITCHEN','Cocina & Menaje');
@define('PLUGIN_EVENT_AMAZONCHOOSER_MAGAZINE','Revistas');
@define('PLUGIN_EVENT_AMAZONCHOOSER_MP3DOWNLOADS','Descargas de MP3');
@define('PLUGIN_EVENT_AMAZONCHOOSER_MUSIC','Música');
@define('PLUGIN_EVENT_AMAZONCHOOSER_MUSICALINST','Instrumentos musicales');
@define('PLUGIN_EVENT_AMAZONCHOOSER_MUSICTRACKS','Pistas de música');
@define('PLUGIN_EVENT_AMAZONCHOOSER_OFFICEPROD','Artículos de oficina');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PETS','Suministros para mascotas');
@define('PLUGIN_EVENT_AMAZONCHOOSER_OUTDOOR','Aire libre');
@define('PLUGIN_EVENT_AMAZONCHOOSER_COMPUTERS','Ordenadores');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PHOTO','Cámara y fotografía');
@define('PLUGIN_EVENT_AMAZONCHOOSER_SHOES','Zapatos');
@define('PLUGIN_EVENT_AMAZONCHOOSER_SOFTWARE','Software');
@define('PLUGIN_EVENT_AMAZONCHOOSER_SOFTWAREVIDEO','Software y videojuegos');
@define('PLUGIN_EVENT_AMAZONCHOOSER_SPORTGOODS','Artículos deportivos');
@define('PLUGIN_EVENT_AMAZONCHOOSER_TOOLS','Herramientas');
@define('PLUGIN_EVENT_AMAZONCHOOSER_TOYS','Juguetes y Juegos');
@define('PLUGIN_EVENT_AMAZONCHOOSER_VHS','VHS');
@define('PLUGIN_EVENT_AMAZONCHOOSER_VIDEO','Vídeo');
@define('PLUGIN_EVENT_AMAZONCHOOSER_COMPUTERGAMES','Ordenadores y Vídeo-juegos');
@define('PLUGIN_EVENT_AMAZONCHOOSER_WATCHES','Relojes');
@define('PLUGIN_EVENT_AMAZONCHOOSER_WIRELESS','Wireless');
@define('PLUGIN_EVENT_AMAZONCHOOSER_WIRELESSACC','Accesorios Wireless');
@define('PLUGIN_EVENT_AMAZONCHOOSER_APPLIANCES','Periféricos');
@define('PLUGIN_EVENT_AMAZONCHOOSER_ARTSANDCRAFTS','Arte y artesanía');
@define('PLUGIN_EVENT_AMAZONCHOOSER_BLENDED','Mezcla');
@define('PLUGIN_EVENT_AMAZONCHOOSER_GARDEN','Jardín');
@define('PLUGIN_EVENT_AMAZONCHOOSER_HOME','Casa');
@define('PLUGIN_EVENT_AMAZONCHOOSER_MARKETPLACE','Mercado (Marketplace)');
@define('PLUGIN_EVENT_AMAZONCHOOSER_MISC','Miscelánea');
@define('PLUGIN_EVENT_AMAZONCHOOSER_MOBILEAPP','Aplicaciones móviles');
@define('PLUGIN_EVENT_AMAZONCHOOSER_OUTLET','Outlet');
@define('PLUGIN_EVENT_AMAZONCHOOSER_UNBOXVIDEO','Unbox Video');
@define('PLUGIN_EVENT_AMAZONCHOOSER_INVALIDINDEX','Índice inválido');
@define('PLUGIN_EVENT_AMAZONCHOOSER_NORESULTS','No se devolvieron resultados.');
@define('PLUGIN_EVENT_AMAZONCHOOSER_NORESULTS_DESC','No se devolvieron resultados de Amazon. Por favor, prueba de nuevo con palabras distintas.');
@define('PLUGIN_EVENT_AMAZONCHOOSER_UNKNOWNERROR','Ocurrió un error desconocido.');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PARSEERROR','Ocurrió un error de analisis gramatical. Por favor, compruebe que el resultado era XML.');
@define('PLUGIN_EVENT_AMAZONCHOOSER_HTTPREQFAIL','Petición HTTP fallida');
@define('PLUGIN_EVENT_AMAZONCHOOSER_REQUEST','Petición');
@define('PLUGIN_EVENT_AMAZONCHOOSER_RESPONSE','Respuesta');
@define('PLUGIN_EVENT_AMAZONCHOOSER_NOIMAGE','No hay imagen disponible');
@define('PLUGIN_EVENT_AMAZONCHOOSER_SETTINGS_PROBLEM','La causa más común de este error es una mala configuración del plugin. Por favor, consulte la documentación y compruebe la configuración del plugin.');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PLUGINPROBLEM','Conflicto de versiones con la biblioteca Amazon.');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PLUGINPROBLEM_DESC','El plugin Botón de Amazon Media depende de una versión más reciente del archivo "Amazon_s9y_lib.php. Por favor, comprueba para asegurarte de que todos tus plugin están actualizados.');
?>
