<?php

    /**
     * @version $Revision$
     * @author Jabrwock <jabrwock@gmail.com>
     * EN-Revision: Revision of lang_en.inc.php
     * Mar 02, 2006
     * Version 0.1
     */

@define('PLUGIN_WEBPASTIES_NAME', 'WebPasties');
@define('PLUGIN_WEBPASTIES_DESC', 'WebPasties allow you to manage things like RSS feeds, polls, event calendars, and IM status buttons. (stackable)');
@define('PLUGIN_WEBPASTIES_CHECK_BELOW', 'Check below for instructions on where to find this.');
@define('PLUGIN_WEBPASTIES_TITLE', 'Title');
@define('PLUGIN_WEBPASTIES_TITLE_DESC', 'The header to appear above your WebPastie. Leave blank for no title.');
@define('PLUGIN_WEBPASTIES_TITLE_ERR', 'Invalid Title, please enter un-coded content. Use CSS stylesheet to change title appearance.');
@define('PLUGIN_WEBPASTIES_MODE', 'Mode');
@define('PLUGIN_WEBPASTIES_MODE_DESC', 'The mode of the webpastie. '. PLUGIN_WEBPASTIES_CHECK_BELOW);
@define('PLUGIN_WEBPASTIES_MODE_SCROLL', 'RSS Feed - scroll');
@define('PLUGIN_WEBPASTIES_MODE_CAL', 'Event Calendar - cal');
@define('PLUGIN_WEBPASTIES_MODE_POLL', 'Web Poll - poll');
@define('PLUGIN_WEBPASTIES_MODE_IM', 'IM status - im');
@define('PLUGIN_WEBPASTIES_MID', 'mID');
@define('PLUGIN_WEBPASTIES_MID_DESC', 'Your WebPasties User ID #. '. PLUGIN_WEBPASTIES_CHECK_BELOW);
@define('PLUGIN_WEBPASTIES_MID_ERR', 'Invalid mID. Please enter a number. '. PLUGIN_WEBPASTIES_CHECK_BELOW);
@define('PLUGIN_WEBPASTIES_ID', 'WebPastie ID');
@define('PLUGIN_WEBPASTIES_ID_DESC', 'The ID # of the webpastie. '. PLUGIN_WEBPASTIES_CHECK_BELOW);
@define('PLUGIN_WEBPASTIES_ID_ERR', 'Invalid WebPastie ID. Please enter a number. '. PLUGIN_WEBPASTIES_CHECK_BELOW);
@define('PLUGIN_WEBPASTIES_EXAMPLE', '<p>Check <a href="http://www.webpasties.com">WebPasties.com</a> to manage your individual webpasties. Once you have created them, their mode, id, and mid will not change, but you can still customize them on the webpasties website. <BR><BR> Below is an example of the RSS feed HTML code generated by WebPasties. The highlighted sections are needed for this plugin');
    
/* vim: set sts=4 ts=4 expandtab: */
?>
