<?php # $Id$

/**
 *  @version $Revision$
 *  @author Translator Name <yourmail@example.com>
 *  EN-Revision: Revision of lang_en.inc.php
 */

@define('PLUGIN_EVENT_AMAZONCHOOSER_TITLE', 'Amazon Media Button');
@define('PLUGIN_EVENT_AMAZONCHOOSER_DESC', 'Adds a button to allow Amazon.com search which are insertable into your entry');
@define('PLUGIN_EVENT_AMAZONCHOOSER_MEDIA_BUTTON', 'Amazon Media');
@define('PLUGIN_EVENT_AMAZONCHOOSER_DEV_TOKEN', 'Developer Access Key ID');
@define('PLUGIN_EVENT_AMAZONCHOOSER_DEV_TOKEN_DESC', 'The developer Access Key ID to use.  You must register with Amazon to receive this.');
@define('PLUGIN_EVENT_AMAZONCHOOSER_DEV_SECRET','Amazon Developer Secret Access key.');
@define('PLUGIN_EVENT_AMAZONCHOOSER_DEV_SECRET_DESC','Your Amazon Developer Secret Access key, available with your Amazon account.');
@define('PLUGIN_EVENT_AMAZONCHOOSER_ASSOCIATE_ID', 'Amazon Associate ID');
@define('PLUGIN_EVENT_AMAZONCHOOSER_ASSOCIATE_ID_DESC', 'Your Amazon Associate ID');
@define('PLUGIN_EVENT_AMAZONCHOOSER_SERVER', 'Default Server');
@define('PLUGIN_EVENT_AMAZONCHOOSER_SERVER_DESC', 'Amazon server you wish to use for localization');
@define('PLUGIN_EVENT_AMAZONCHOOSER_GERMANY', 'Germany');
@define('PLUGIN_EVENT_AMAZONCHOOSER_JAPAN', 'Japan');
@define('PLUGIN_EVENT_AMAZONCHOOSER_UK', 'United Kingdom');
@define('PLUGIN_EVENT_AMAZONCHOOSER_US', 'United States');
@define('PLUGIN_EVENT_AMAZONCHOOSER_CA', 'Canada');
@define('PLUGIN_EVENT_AMAZONCHOOSER_FR', 'France');
@define('PLUGIN_EVENT_AMAZONCHOOSER_SEARCH', 'Search');
@define('PLUGIN_EVENT_AMAZONCHOOSER_SEARCH_DESC', 'Enter a keyword to search for:');
@define('PLUGIN_EVENT_AMAZONCHOOSER_CLICK', 'Click on the item you are searching for:');
@define('PLUGIN_EVENT_AMAZONCHOOSER_CHOSE', 'You chose ');
@define('PLUGIN_EVENT_AMAZONCHOOSER_AUTHOR', 'Author');
@define('PLUGIN_EVENT_AMAZONCHOOSER_RELEASED', 'Released');
@define('PLUGIN_EVENT_AMAZONCHOOSER_MANUFACTURER', 'Manufacturer');
@define('PLUGIN_EVENT_AMAZONCHOOSER_DISTRIBUTOR', 'Distributor');
@define('PLUGIN_EVENT_AMAZONCHOOSER_STARRING', 'Starring');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PUBLISHER', 'Publisher');
@define('PLUGIN_EVENT_AMAZONCHOOSER_ARTISTS', 'Artist');
@define('PLUGIN_EVENT_AMAZONCHOOSER_DIRECTOR', 'Director');
@define('PLUGIN_EVENT_AMAZONCHOOSER_NUMPAGES', 'Number of pages');
@define('PLUGIN_EVENT_AMAZONCHOOSER_ISBN', 'ISBN');
@define('PLUGIN_EVENT_AMAZONCHOOSER_RUNNING', 'Running Time');
@define('PLUGIN_EVENT_AMAZONCHOOSER_FORMAT', 'Format');
@define('PLUGIN_EVENT_AMAZONCHOOSER_EAN', 'EAN');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PRODUCTTITLE','Title');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PLATFORM','Platform');
@define('PLUGIN_EVENT_AMAZONCHOOSER_GENRE','Genre');
@define('PLUGIN_EVENT_AMAZONCHOOSER_ESRBAGERATING','ESRB Rating');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PRICE','Price');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PUBLISHED','Published');
@define('PLUGIN_EVENT_AMAZONCHOOSER_DISTINCTURL','More Information');
@define('PLUGIN_EVENT_AMAZONCHOOSER_TECHDETAILS','Technical Details');
@define('PLUGIN_EVENT_AMAZONCHOOSER_CUSTOMERREVIEWS','See Customer Reviews');
@define('PLUGIN_EVENT_AMAZONCHOOSER_ALLOFFERS','See All Offers');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PRODUCTGROUP','Product Type:');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PRODUCTLANGUAGE','Language');
@define('PLUGIN_EVENT_AMAZONCHOOSER_AUDIENCERATING','Rating');
@define('PLUGIN_EVENT_AMAZONCHOOSER_NEW','new');
@define('PLUGIN_EVENT_AMAZONCHOOSER_USED','used');
@define('PLUGIN_EVENT_AMAZONCHOOSER_COLLECTABLE','collectable');
@define('PLUGIN_EVENT_AMAZONCHOOSER_REFURBISHED','refurbished');
@define('PLUGIN_EVENT_AMAZONCHOOSER_FROM','from');
@define('PLUGIN_EVENT_AMAZONCHOOSER_NOASIN','No ASIN was provided in search.  This is likely a problem in the stored post.');
@define('PLUGIN_EVENT_AMAZONCHOOSER_BRAND','Brand');
@define('PLUGIN_EVENT_AMAZONCHOOSER_MODEL','Model');
@define('PLUGIN_EVENT_AMAZONCHOOSER_NUMDISKS','Number of Disks');
@define('PLUGIN_EVENT_AMAZONCHOOSER_FEATURE','Features');
@define('PLUGIN_EVENT_AMAZONCHOOSER_DISPLAYING','Displaying');
@define('PLUGIN_EVENT_AMAZONCHOOSER_OF','of');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PAGE','page');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PAGES','pages');
@define('PLUGIN_EVENT_AMAZONCHOOSER_ITEMS','items');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PAGELIMIT','Only 400 viewable pages');
@define('PLUGIN_EVENT_AMAZONCHOOSER_ASOF','Information accurate as of');
@define('PLUGIN_EVENT_AMAZONCHOOSER_APPAREL','Apparel');
@define('PLUGIN_EVENT_AMAZONCHOOSER_AUTO','Automotive');
@define('PLUGIN_EVENT_AMAZONCHOOSER_BABY','Baby');
@define('PLUGIN_EVENT_AMAZONCHOOSER_BEAUTY','Beauty');
@define('PLUGIN_EVENT_AMAZONCHOOSER_BOOKS','Books');
@define('PLUGIN_EVENT_AMAZONCHOOSER_CLASSICALMUSIC','Classical Music');
@define('PLUGIN_EVENT_AMAZONCHOOSER_DIGITALMUSIC','Digital Music');
@define('PLUGIN_EVENT_AMAZONCHOOSER_DVD','DVD');
@define('PLUGIN_EVENT_AMAZONCHOOSER_ELECTRONICS','Electronics');
@define('PLUGIN_EVENT_AMAZONCHOOSER_FOREIGNBOOKS','Foreign Books');
@define('PLUGIN_EVENT_AMAZONCHOOSER_GORMETFOOD','Gourmet Food');
@define('PLUGIN_EVENT_AMAZONCHOOSER_GROCERY','Grocery');
@define('PLUGIN_EVENT_AMAZONCHOOSER_HEALTH','Health/Personal Care');
@define('PLUGIN_EVENT_AMAZONCHOOSER_HOBBIES','Hobbies');
@define('PLUGIN_EVENT_AMAZONCHOOSER_HOMEGARDEN','Home/Garden');
@define('PLUGIN_EVENT_AMAZONCHOOSER_HOMEIMPROVE','Home Improvement');
@define('PLUGIN_EVENT_AMAZONCHOOSER_INDUSTRIAL','Industrial');
@define('PLUGIN_EVENT_AMAZONCHOOSER_JEWELRY','Jewelry');
@define('PLUGIN_EVENT_AMAZONCHOOSER_KINDLESTORE','Kindle Store');
@define('PLUGIN_EVENT_AMAZONCHOOSER_KITCHEN','Kitchen & Housewares');
@define('PLUGIN_EVENT_AMAZONCHOOSER_MAGAZINE','Magazines');
@define('PLUGIN_EVENT_AMAZONCHOOSER_MP3DOWNLOADS','MP3 Downloads');
@define('PLUGIN_EVENT_AMAZONCHOOSER_MUSIC','Music');
@define('PLUGIN_EVENT_AMAZONCHOOSER_MUSICALINST','Musical Instruments');
@define('PLUGIN_EVENT_AMAZONCHOOSER_MUSICTRACKS','Music Tracks');
@define('PLUGIN_EVENT_AMAZONCHOOSER_OFFICEPROD','Office Products');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PETS','Pet Supplies');
@define('PLUGIN_EVENT_AMAZONCHOOSER_OUTDOOR','Outdoor Living');
@define('PLUGIN_EVENT_AMAZONCHOOSER_COMPUTERS','Computers');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PHOTO','Camera & Photo');
@define('PLUGIN_EVENT_AMAZONCHOOSER_SHOES','Shoes');
@define('PLUGIN_EVENT_AMAZONCHOOSER_SOFTWARE','Software');
@define('PLUGIN_EVENT_AMAZONCHOOSER_SOFTWAREVIDEO','Software and Video Games');
@define('PLUGIN_EVENT_AMAZONCHOOSER_SPORTGOODS','Sporting Goods');
@define('PLUGIN_EVENT_AMAZONCHOOSER_TOOLS','Tools');
@define('PLUGIN_EVENT_AMAZONCHOOSER_TOYS','Toys & Games');
@define('PLUGIN_EVENT_AMAZONCHOOSER_VHS','VHS');
@define('PLUGIN_EVENT_AMAZONCHOOSER_VIDEO','Video');
@define('PLUGIN_EVENT_AMAZONCHOOSER_COMPUTERGAMES','Computer & Video Games');
@define('PLUGIN_EVENT_AMAZONCHOOSER_WATCHES','Watches');
@define('PLUGIN_EVENT_AMAZONCHOOSER_WIRELESS','Wireless');
@define('PLUGIN_EVENT_AMAZONCHOOSER_WIRELESSACC','Wireless Accessories');
@define('PLUGIN_EVENT_AMAZONCHOOSER_INVALIDINDEX','Invalid Index');
@define('PLUGIN_EVENT_AMAZONCHOOSER_NORESULTS','No results were returned.');
@define('PLUGIN_EVENT_AMAZONCHOOSER_NORESULTS_DESC','No results were returned from Amazon.  Please try the search again with different keywords.');
@define('PLUGIN_EVENT_AMAZONCHOOSER_UNKNOWNERROR','Unknown error occurred.');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PARSEERROR','A parse error occurred.  Please check that the result was XML.');
@define('PLUGIN_EVENT_AMAZONCHOOSER_HTTPREQFAIL','HTTP Request failed.');
@define('PLUGIN_EVENT_AMAZONCHOOSER_REQUEST','Request');
@define('PLUGIN_EVENT_AMAZONCHOOSER_RESPONSE','Response');
@define('PLUGIN_EVENT_AMAZONCHOOSER_NOIMAGE','No Image Available');
@define('PLUGIN_EVENT_AMAZONCHOOSER_SETTINGS_PROBLEM','The most common cause of this error is a mis-configuration of the plugin.  Please consult the documentation and check the plugin configuration.');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PLUGINPROBLEM','Version conflict for Amazon library.');
@define('PLUGIN_EVENT_AMAZONCHOOSER_PLUGINPROBLEM_DESC','The Amazon Media Button plugin depends on a newer version of the file "Amazon_s9y_lib.php".  Please check to make sure all of your plugins are up to date.');
?>
